language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "bigpear0201"
  - git config user.email "bigpear0201@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/bigpear0201/bigpear0201.github.io.git
    - secure: v8rncB3MIouwuk+2o7urHWTCN5O/CLXruiHLwyOj4Ar89sdQhnrso2zOfHppyRZ+SN4D/it4V7pKDqmsduX1K1MJ1aneSFm1KsZLu4+hMLS3sklOdRXAt6vk8JK8JhvQ41pKwNpYSs4txAL+h1Kph3RMUeqxo8a7G2n5UULvepPVG8fsoPr6ZIck63ScoDhs9E4BlEJa39XkuqvdeKMyUntxrk0hbDBal60wMvap7YveAaRIOSlwtBVBz5VTYkqV8A5uuTEm9jtyRfRAupISKElajGPCqKeFAT1mEL175/6lfiO87Siy6O9g0Q2rzT0NjqusuXQO3Q5TkqpwgQ1WSe5mv1x6pwy1HKu53Avj2q7ksJ542roKO+11SRSeC+q/ydyAhOTYgJgRcjUNmlaJTm5NiT4xmAJ6fbLeiQyLwR/BBUiPJp6Y5M2Pe5uwlZk9BcFE7y8tZFXnDFdjAzJ3vZOZRqtNfK2ytuR4LYf7M3Fs43TooMmLpvJs/kbmV/T9liCnBVSZQYgQqozorpQIfW+o+OVBPBnd8swzvPIosATNvWpIvYXTdHAKWdklxURr1HIT/Rs3wtL53FPdBqWoIHBwBPbycNk/qJdJxyi+e62KmzHRhHjq6cBYWMXwVJKOq4mA2iPOUEzWjJpiZ9sc+AIdMW/mxeorHpl0QOqWw04=
