language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo g
after_script:
  #- cd ./public
  #- git init
  - git config user.name "bigpear0201"
  - git config user.email "bigpear0201@gmail.com"
  #- git add .
  #- git commit -m "Update docs"
  #- git push --force --quiet "https://${BLOG_TOKEN}@${GH_REF}" master:master
  - sed -i'' "s~git@github.com:bigpear0201/bigpear0201.github.io.git~https://${BLOG_TOKEN}@${GH_REF}~" _config.yml
  - hexo d

env:
  global:
  - GH_REF: github.com/bigpear0201/bigpear0201.github.io.git
  - secure: nDxzI/sQc8HhnMPxVyzY0Y+a4zmo130rL2rPVBSWkDG2cireoznHzzFeWPCTESkYmOZocyKdORWqmGA00wzXXS9IDDidCRN+noPrPjHmUYQVaQRCSd40YFJqAh0dlQovbl1yO0UJHf+hyDImgdn5o/CNCRjEHKrWoYXckH6K3xRz/IDq+i2/U5+HSUK0nKy3lb9PQU4JfUTwma+WPSl5sJ9u77MNl6dQwk0PSVtEstsqUK+4hzXHeCEh+Nr5FeCKW31SyrIo3DdovhJ9mkEIKhRUZGY7bnBShzw9MlIkbqk0hCqxn1bhzvaa2rYqCkiS+GhFCa5Jo+ZrreNkTH3o7e+TKZRr17OXOBEDpSZeE5fHgqCD4jjyG3U1f1F3yzE3x0TLlctCpB6MFAhZezlnaPxW5Kr1IhRBNQx0DGghrIfnCGl+rMylRB1Qb3oj5O/o1pOfbhZecP49NKB6YAUsJb0ejGaVf6fJghb8TuT5XKPm80ZvYLujIiw9TSQbcr87joaBamao6gpdl/hbbJ/4e+b4hpVR4up3Ue33ykZVmTyWwHznvpOaJbi2fvJKKe4vL+cPTbGXhKv01CMo6bn72FICRQBITp2ArPKKL9GXZWwzMSYxFSomxoNExMIM7Wx9l92Grak+Myp+MvST4WtqO1PECS7oC2dlBi6fCnTq/Ao=
